
// FakeData.js
export const products = [
	{
        id: 1,
        name: "Pia",
        price: 10.5,
        category: "dessert",
        description: "fisdnvblavajs v",
        quantity: 1,
        imgSrc: "https://readymadeui.com/images/product9.webp",
        features: [
            "Made with fresh ingredients",
            "Delicious and sweet",
            "Perfect for any occasion",
            "Baked to perfection"
          ],
    },
    {
        id: 2,
        name: "Cua Hoang De",
        price: 20.5,
        category: "food",
        description: "fisdnvblavajs v",
        quantity: 1,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 3,
        name: "Soda",
        price: 1.5,
        category: "drink",
        description: "fisdnvblavajs v",
        quantity: 0,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 4,
        name: "Lays Xanh La",
        price: 0.5,
        category: "snack",
        description: "fisdnvblavajs v",
        quantity: 1,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 5,
        name: "Banh Pia",
        price: 10.5,
        category: "dessert",
        description: "fisdnvblavajs v",
        quantity: 1,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 6,
        name: "Cua Hoang De",
        price: 20.5,
        category: "food",
        description: "fisdnvblavajs v",
        quantity: 1,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 7,
        name: "Soda",
        price: 1.5,
        category: "drink",
        description: "fisdnvblavajs v",
        quantity: 0,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 8,
        name: "Lays Xanh La",
        price: 0.5,
        category: "snack",
        description: "fisdnvblavajs v",
        quantity: 0,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 9,
        name: "Banh 21e2",
        price: 10.5,
        category: "dessert",
        description: "fisdnvblavajs v",
        quantity: 0,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 10,
        name: "Cua 1e213 De",
        price: 20.5,
        category: "food",
        description: "fisdnvblavajs v",
        quantity: 1,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 11,
        name: "12",
        price: 1.5,
        category: "drink",
        description: "fisdnvblavajs v",
        quantity: 0,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 12,
        name: "Lays 2 La",
        price: 0.5,
        category: "snack",
        description: "fisdnvblavajs v",
        quantity: 1,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 13,
        name: "Banh 21",
        price: 10.5,
        category: "dessert",
        description: "fisdnvblavajs v",
        quantity: 1,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 14,
        name: "Cua 2 1",
        price: 20.5,
        category: "food",
        description: "fisdnvblavajs v",
        quantity: 1,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 15,
        name: "afe",
        price: 1.5,
        category: "drink",
        description: "fisdnvblavajs v",
        quantity: 0,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 16,
        name: "e33",
        price: 0.5,
        category: "snack",
        description: "fisdnvblavajs v",
        quantity: 1,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 17,
        name: "2 Pia",
        price: 10.5,
        category: "dessert",
        description: "fisdnvblavajs v",
        quantity: 1,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 18,
        name: "Cua 2 De",
        price: 20.5,
        category: "food",
        description: "fisdnvblavajs v",
        quantity: 1,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 19,
        name: "afe",
        price: 1.5,
        category: "drink",
        description: "fisdnvblavajs v",
        quantity: 0,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
    {
        id: 20,
        name: "e33",
        price: 0.5,
        category: "snack",
        description: "fisdnvblavajs v",
        quantity: 1,
        imgSrc: "https://readymadeui.com/images/product9.webp",
    },
]
