//ProductMockData.js
export const products = [
	{
		id: 1,
		name: 'Pia',
		price: 10.5,
		category: 'dessert',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],

		reviews: [
			{
				reviewer: 'Sinl 1',
				rating: 5,
				comment: 'Anh này mờ lem.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane 2',
				rating: 4,
				comment: 'Mờ lem mà tên kì Pịa.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily 3',
				rating: 5,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
			{
				reviewer: 'John 4',
				rating: 5,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane 5',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily 6',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
			{
				reviewer: 'John 7',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane 8',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily 9',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
			{
				reviewer: 'John 10',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane 11',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily 12',
				rating: 1,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 2,
		name: 'Cua Hoang De',
		price: 20.5,
		category: 'food',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],

		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 3,
		name: 'Soda',
		price: 1.5,
		category: 'drink',
		description: 'fisdnvblavajs v',
		quantity: 0,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],

		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 4,
		name: 'Lays Xanh La',
		price: 0.5,
		category: 'snack',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 5,
		name: 'Banh Pia',
		price: 10.5,
		category: 'dessert',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 6,
		name: 'Cua Hoang De',
		price: 20.5,
		category: 'food',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 7,
		name: 'Soda',
		price: 1.5,
		category: 'drink',
		description: 'fisdnvblavajs v',
		quantity: 0,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 8,
		name: 'Lays Xanh La',
		price: 0.5,
		category: 'snack',
		description: 'fisdnvblavajs v',
		quantity: 0,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 9,
		name: 'Banh 21e2',
		price: 10.5,
		category: 'dessert',
		description: 'fisdnvblavajs v',
		quantity: 0,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 10,
		name: 'Cua 1e213 De',
		price: 20.5,
		category: 'food',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 11,
		name: '12',
		price: 1.5,
		category: 'drink',
		description: 'fisdnvblavajs v',
		quantity: 0,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 12,
		name: 'Lays 2 La',
		price: 0.5,
		category: 'snack',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 13,
		name: 'Banh 21',
		price: 10.5,
		category: 'dessert',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 14,
		name: 'Cua 2 1',
		price: 20.5,
		category: 'food',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 15,
		name: 'afe',
		price: 1.5,
		category: 'drink',
		description: 'fisdnvblavajs v',
		quantity: 0,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 16,
		name: 'e33',
		price: 0.5,
		category: 'snack',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 17,
		name: '2 Pia',
		price: 10.5,
		category: 'dessert',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 18,
		name: 'Cua 2 De',
		price: 20.5,
		category: 'food',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 19,
		name: '2222',
		price: 1.5,
		category: 'drink',
		description: 'fisdnvblavajs v',
		quantity: 0,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
    {
		id: 20,
		name: '11',
		price: 1.5,
		category: 'drink',
		description: 'fisdnvblavajs v',
		quantity: 0,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
    {
		id: 21,
		name: '2221113',
		price: 1.5,
		category: 'drink',
		description: 'fisdnvblavajs v',
		quantity: 0,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
    {
		id: 22,
		name: '31ewf ',
		price: 1.5,
		category: 'drink',
		description: 'fisdnvblavajs v',
		quantity: 0,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
    {
		id: 23,
		name: '2 rfwe',
		price: 1.5,
		category: 'drink',
		description: 'fisdnvblavajs v',
		quantity: 0,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
]
