export const products = [
	{
		id: 1,
		name: 'Pia Cake',
		price: 10.5,
		category: 'dessert',
		subcategory: 'cake',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'Sinl 1',
				rating: 5,
				comment: 'Anh này mờ lem.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane 2',
				rating: 4,
				comment: 'Mờ lem mà tên kì Pịa.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily 3',
				rating: 5,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
			// Additional reviews for Pia Cake
		],
	},
	{
		id: 2,
		name: 'King Crab',
		price: 20.5,
		category: 'food',
		subcategory: 'seafood',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 3,
		name: 'Sparkling Soda',
		price: 1.5,
		category: 'drink',
		subcategory: 'carbonated',
		description: 'fisdnvblavajs v',
		quantity: 0,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 4,
		name: 'Lays Green',
		price: 0.5,
		category: 'snack',
		subcategory: 'chips',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 5,
		name: 'Banh Pia',
		price: 10.5,
		category: 'dessert',
		subcategory: 'pastry',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
	{
		id: 6,
		name: 'King Crab',
		price: 20.5,
		category: 'food',
		subcategory: 'seafood',
		description: 'fisdnvblavajs v',
		quantity: 1,
		img: [
			'https://readymadeui.com/images/product3.webp',
			'https://readymadeui.com/images/product2.webp',
			'https://readymadeui.com/images/product1.webp',
		],
		reviews: [
			{
				reviewer: 'John Doe',
				rating: 4,
				comment: 'Very comfortable and soft. It exceeded my expectations.',
				avatar: '/images/avatars/john_doe.jpg',
				date: '2024-09-01',
			},
			{
				reviewer: 'Jane Smith',
				rating: 2,
				comment: 'Absolutely love this blanket! It’s the perfect size and warmth.',
				avatar: '/images/avatars/jane_smith.jpg',
				date: '2024-09-05',
			},
			{
				reviewer: 'Emily Johnson',
				rating: 3,
				comment: 'It’s decent but I expected it to be a bit thicker for the price.',
				avatar: '/images/avatars/emily_johnson.jpg',
				date: '2024-09-10',
			},
		],
	},
]