export const vouchers = [
    {
        id: 1,
        name: 'Black Friday Sale',
        description: 'Up to 50% off on selected items during Black Friday!',
        expiredDate: '2024-11-25',
        reducedPercent: 50,
        maxReducing: 200000, // This is an example of a large max reducing value
        quantity: 100,
        image: 'https://png.pngtree.com/background/20210711/original/pngtree-simple-atmosphere-vip-voucher-coupon-background-picture-image_1086943.jpg', // Placeholder image URL
        isDeleted: false,
    },
    {
        id: 2,
        name: 'Cyber Monday Discount',
        description: 'Exclusive 30% off during Cyber Monday!',
        expiredDate: '2024-12-02',
        reducedPercent: 30,
        maxReducing: 150000,
        quantity: 200,
        image: 'https://png.pngtree.com/background/20210711/original/pngtree-simple-atmosphere-vip-voucher-coupon-background-picture-image_1086943.jpg',
        isDeleted: false,
    },
    {
        id: 3,
        name: 'Christmas Special Offer',
        description: 'Special 40% off on all items during Christmas season!',
        expiredDate: '2024-12-25',
        reducedPercent: 40,
        maxReducing: 300000,
        quantity: 50,
        image: 'https://readymadeui.com/https://png.pngtree.com/background/20210711/original/pngtree-simple-atmosphere-vip-voucher-coupon-background-picture-image_1086943.jpgimages/voucher3.webp',
        isDeleted: false,
    },
    {
        id: 4,
        name: 'Spring Sale',
        description: 'Enjoy a 20% discount on new arrivals this Spring!',
        expiredDate: '2024-04-10',
        reducedPercent: 20,
        maxReducing: 100000,
        quantity: 150,
        image: 'https://readyhttps://png.pngtree.com/background/20210711/original/pngtree-simple-atmosphere-vip-voucher-coupon-background-picture-image_1086943.jpgmadeui.com/images/voucher4.webp',
        isDeleted: false,
    },
    {
        id: 5,
        name: 'Grand Opening Discount',
        description: 'Celebrate the grand opening with a 10% discount on all purchases!',
        expiredDate: '2024-10-15',
        reducedPercent: 10,
        maxReducing: 50000,
        quantity: 300,
        image: 'https://readymadeui.https://png.pngtree.com/background/20210711/original/pngtree-simple-atmosphere-vip-voucher-coupon-background-picture-image_1086943.jpgcom/images/voucher5.webp',
        isDeleted: false,
    }
];
